# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20171016_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number_of_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
