# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_number_of_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
