# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_item_sum_of_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rated',
            field=models.ManyToManyField(related_name='users_rated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
