# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20171018_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
